---
shallow_clone: true
platform:
  - x64
environment:
  ruby_version: "24-%Platform%"
  zlib_version: "1.2.11"
  matrix:
    - vs: "120"
    - MSYSTEM: "MINGW64"
    - MSYSTEM: "MINGW32"
install:
  - IF DEFINED MSYSTEM (
      c:/msys64/usr/bin/bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/appveyor_mingw.sh install_script"
    ) else (
      appveyor_mswin.cmd install_script
    )
build_script:
  - IF DEFINED MSYSTEM (
      c:/msys64/usr/bin/bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/appveyor_mingw.sh build_script"
    ) else (
      appveyor_mswin.cmd build_script
    )
test_script:
  - IF DEFINED MSYSTEM (
      c:/msys64/usr/bin/bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/appveyor_mingw.sh test_script"
    ) else (
      appveyor_mswin.cmd test_script
    )
matrix:
  fast_finish: false
